import type { ExplorePreset } from "@/types";

export const EXPLORE_PRESETS: ExplorePreset[] = [
  {
    id: "old-money",
    title: "Old Money",
    description: "Understated luxury. Timeless silhouettes, neutral tones.",
    prompt: "old money dinner date",
    filters: { budgetMax: 350, retailers: ["Banana Republic", "Uniqlo", "Zara"], mixRetailers: true },
    accentColor: "#C8A882",
    bgColor: "#FAF8F5",
    previewColors: ["#FAF8F5", "#E8E4DD", "#C8B89A", "#2D2926"],
  },
  {
    id: "streetwear",
    title: "Streetwear",
    description: "Urban edge. Oversized fits, bold statements, city ready.",
    prompt: "streetwear concert fit",
    filters: { budgetMax: 250, retailers: ["Nike", "H&M", "ASOS"], mixRetailers: true },
    accentColor: "#2D2926",
    bgColor: "#1A1714",
    previewColors: ["#2D2926", "#4B5563", "#6B7280", "#FAF8F5"],
  },
  {
    id: "minimalist",
    title: "Minimalist",
    description: "Less is more. Clean lines, monochrome, elevated basics.",
    prompt: "minimalist clean outfit",
    filters: { budgetMax: 300, retailers: ["Uniqlo", "Zara", "Banana Republic"], mixRetailers: true },
    accentColor: "#9A8E82",
    bgColor: "#F5F4F2",
    previewColors: ["#FAF8F5", "#E8E4DD", "#9A8E82", "#2D2926"],
  },
  {
    id: "coastal",
    title: "Coastal / Beach",
    description: "Sun-soaked ease. Linen, nautical, light and breezy.",
    prompt: "coastal beach day outfit",
    filters: { budgetMax: 200, retailers: ["Zara", "H&M", "Free People"], mixRetailers: true },
    accentColor: "#5B8AC4",
    bgColor: "#EFF6FF",
    previewColors: ["#EFF6FF", "#BFDBFE", "#5B8AC4", "#C8A882"],
  },
  {
    id: "business-casual",
    title: "Business Casual",
    description: "Office-ready but never boring. Sharp, confident, polished.",
    prompt: "business casual office outfit",
    filters: { budgetMax: 300, retailers: ["Banana Republic", "Uniqlo", "Zara"], mixRetailers: true },
    accentColor: "#1A3A6B",
    bgColor: "#F8F9FA",
    previewColors: ["#2D2926", "#1A3A6B", "#E8E4DD", "#C8B89A"],
  },
  {
    id: "night-out",
    title: "Night Out",
    description: "Turn heads. Sleek, confident, effortlessly glam.",
    prompt: "night out party outfit",
    filters: { budgetMax: 280, retailers: ["Zara", "ASOS", "Abercrombie"], mixRetailers: true },
    accentColor: "#C9A84C",
    bgColor: "#18171A",
    previewColors: ["#2D2926", "#C9A84C", "#4A4036", "#FAF8F5"],
  },
];
